namespace PluginBaseLib
{
    public static class Quotes
    {
        public static readonly string[] SmallGods =
        {
            "Chain letters, said the Tyrant. The Chain Letter to the Ephebians. Forget Your Gods. Be Subjugated. Learn to Fear. Do not break the chain -- the last people who did woke up one morning to find fifty thousand armed men on their lawn.",
            "It\"s a god-eat-god world.",
            "You can\"t trample infidels when you\"re a tortoise. I mean, all you could do is give them a meaningful look.",
            "That\"s right, he said. We\"re philosophers. We think, therefore we am.",
            "His philosophy was a mixture of three famous schools -- the Cynics, the Stoics and the Epicureans -- and summed up all three of them in his famous phrase, You can\"t trust any bugger further than you can throw him, and there\"s nothing you can do about it, so let\"s have a drink.",
            "Dhblah sidled closer. This was not hard. Dhblah sidled everywhere. Crabs thought he walked sideways.",
            "One day a tortoise will learn how to fly.",
            "History, contrary to popular theories, is kings and dates and battles.",
            "And it came to pass that in time the Great God Om spake unto Brutha, the Chosen One: Psst!",
            "Brother Preptil, the master of the music, had described Brutha\"s voice as putting him in mind of a disappointed vulture arriving too late at the dead donkey.",
            "There\"s very good eating on one of these, you know.",
            "Pets are always a great help in times of stress. And in times of starvation too, o\"course.",
            "Words are the litmus paper of the minds. If you find yourself in the power of someone who will use the word commence in cold blood, go somewhere else very quickly. But if they say Enter, don\"t stop to pack.",
            "The labyrinth of Ephebe is ancient and full of one hundred and one amazing things you can do with hidden springs, razor-sharp knives, and falling rocks.",
            "Ah. Philosophy, said Om.",
            "Not a man to mince words. People, yes. But not words.",
            "SQUEAK.",
            "Bishops move diagonally. That\"s why they often turn up where the kings don\"t expect them to be.",
            "Eureka, he said. Going to have a bath then?",
            "Cuius testiculos habes, habeas cardia et cerebellum.",
            "Are you a philosopher? Where\"s your sponge?",
            "REMIND ME AGAIN, he said, HOW THE LITTLE HORSE-SHAPED ONES MOVE.",
            "Go on, do Deformed Rabbit... it\"s my favourite.",
            "Oh, a very useful philosophical animal, your average tortoise. Outrunning metaphorical arrows, beating hares in races... very handy.",
            "Gravity is a habit that is hard to shake off.",
            "The trouble with being a god is that you\"ve got no one to pray to.",
            "There are hardly any excesses of the most crazed psychopath that cannot easily be duplicated by a normal kindly family man who just comes in to work every day and has a job to do.",
            "The people who really run organizations are usually found several levels down, where it is still possible to get things done.",
            "Guilt was the grease in which the wheels of the authority turned.",
            "Most gods find it hard to walk and think at the same time.",
            "When the least they could do to you was everything, then the most they could do to you suddenly held no terror.",
            "What\"s a philosopher ? said Brutha. Someone who\"s bright enough to find a job with no heavy lifting, said a voice in his head.",
            "Slave is an Ephebian word. In Om we have no word for slave, said Vorbis. So I understand, said the Tyrant. I imagine that fish have no word for water.",
            "He says gods like to see an atheist around. Gives them something to aim at.",
            "You\"re not one of us. I don\"t think I\"m one of them, either, said Brutha. I\"m one of mine.",
            "Simony\"s eyes gleamed with the gleam of a man who had seen the future and found it covered with armour plating.",
            "All holy piety in public, and all peeled grapes and self-indulgence in private.",
            "When you can flatten entire cities at a whim, a tendency towards quiet reflection and seeing-things-from-the-other-fellow\"s-point- of-view is seldom necessary.",
            "Take it from me, whenever you see a bunch of buggers puttering around talking about truth and beauty and the best way of attacking Ethics, you can bet your sandals it\"s all because dozens of other poor buggers are doing all the real work around the place.",
            "Why do you bother with him? He\"s had thousands of people killed! Yes, but perhaps he thought that you wanted it.",
            "The figures looked more or less human. And they were engaged in religion. You could tell by the knives (it\"s not murder if you do it for a god).",
            "The trouble was that he was talking in philosophy, but they were listening in gibberish.",
            "He\"s muffed it, said Simony. he could have done anything with them. And he just told them the facts. You can\"t inspire people with facts. They need a cause. They need a symbol.",
            "You can\"t find a hermit to teach you herming, because of course that rather spoils the whole thing.",
            "Om began to feel the acute depression that steals over every realist in the presence of an optimist.",
            "All the other prophets came back with commandments! Where they get them? I ... suppose they made them up. You get them from the same place.",
            "Brutha tried to nod, and thought: I\"m on everyone\"s side. It\"d be nice if, just for once, someone was on mine.",
            "Probably the last man who knew how it worked had been tortured to death years before. Or as soon as it was installed. Killing the creator was a traditional method of patent protection.",
            "Give anyone a lever long enough and they can change the world. It\"s unreliable levers that are the problem.",
            "Now we\"ve got a truth to die for! No. Men should die for lies. But the truth is too precious to die for.",
            "YOU HAVE PERHAPS HEARD THE PHRASE THAT HELL IS OTHER PEOPLE? Yes. Yes, of course. Death nodded. IN TIME, he said, YOU WILL LEARN THAT IT IS WRONG.",
            "I used to think that I was stupid, and then I met philosophers.",
            "I like the idea of democracy. You have to have someone everyone distrusts, said Brutha. That way, everyone\"s happy.",
            "That\"s why it\"s always worth having a few philosophers around the place. One minute it\"s all Is Truth Beauty and Is Beauty Truth, and Does A Falling Tree in the Forest Make A Sound if There\"s No one There to Hear It, and then just when you think they\"re going to start dribbling one of \"em says, Incidentally, putting a thirty-foot parabolic reflector on a high place to shoot the rays of the sun at an enemy\"s ships would be a very interesting demonstration of optical principles."
        };
    }
}
